### ISSUE TITLE
Request to add a license to your project

### ISSUE THREAD

**Issue by Linesmerrill** [eclipse-vertx/.eclipsefdn#13]
#### Describe the feature

Hi, I am familiar with your project and I noticed that it does not have a LICENSE file in the root directory. I would like to suggest that you add a license to your project so it can be freely used, modified, repurposed, or shared by the open source community. You can find information on various licenses [here](https://opensource.org/licenses). To choose the right license for your project, check out [choosealicense.com](https://choosealicense.com/). If you have already chosen a license, to apply this license in a way that the community can recognize, you can add a file in the root directory of your default branch named LICENSE containing your license.

#### Use cases

Allow open source community to use, modify and repurpose your project

#### Contribution

This should be added by the owner of the repo, since they would need to confirm the proper license.

**Comment by netomi** [comment]
This repo only contains configuration files related to the administration of this project. So far we did not see the need to add a license file to them, but we might consider that in the future.

**Comment by Linesmerrill** [comment]
Yeah 100% makes sense to me! Thanks for the quick reply, have an awesome day!
